# Path to your oh-my-zsh installation.
echo "$(date) -- .zshrc executed" >> $HOME/.zshrc.log
export ZSH=$HOME/.oh-my-zsh

bindkey -e

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git ruby rails bundler)

# User configuration
export EDITOR=vim
export VISUAL=vim

# History control.
SAVEHIST=100000
HISTSIZE=100000
if [ -e ~/priv/ ]; then
  HISTFILE=~/priv/zsh_history
elif [ -e ~/secure/ ]; then
  HISTFILE=~/secure/zsh_history
else
  HISTFILE=~/.zsh_history
fi
if [ -n "$HISTFILE" -a ! -w $HISTFILE ]; then
  echo
  echo "[31;1m HISTFILE [$HISTFILE] not writable! [0m"
  echo
fi

# export MANPATH="/usr/local/man:$MANPATH"
source $ZSH/oh-my-zsh.sh

# updates to PATH
_prepend_to_path() {
  if [ -d $1 -a -z ${path[(r)$1]} ]; then
    path=($1 $path);
  fi
}

_append_to_path() {
  if [ -d $1 -a -z ${path[(r)$1]} ]; then
    path=($1 $path);
  fi
}

_include () {
  if [ -f "$1" ]; then
    source "$1"
  fi
}

export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
_prepend_to_path /usr/local/sbin
_prepend_to_path /usr/local/bin
_prepend_to_path ~/bin
_prepend_to_path /Applications/Postgres.app/Contents/Versions/latest/bin


# Java
export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

# Go
if [[ "$OSTYPE" == "darwin"* ]]; then
  export GOPATH=$HOME/golang
  export GOROOT=/usr/local/opt/go/libexec
  export GOBIN=$GOPATH/bin
  export PATH=$PATH:$GOPATH:$GOBIN:$GOROOT/bin
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
  export GOPATH=$HOME/golang
  export GOROOT=/usr/local/go
  export GOBIN=$GOPATH/bin
  export PATH=$PATH:$GOROOT/bin:$GOBIN
fi

# Python paths
export PATH=$PATH:/Users/trevoroke/Library/Python/3.7/bin

_include ~/.bash_aliases 
_include ~/.work_aliases.sh


build-ssh-config () {
  echo "building .ssh/config"
  rm ~/.ssh/config

  echo "# autogenerated by build-ssh-config" > ~/.ssh/config
  for file in ~/.ssh/config.d/*; do
    echo "adding $file"
    cat ${file} >> ~/.ssh/config
  done

  chmod 0600 ~/.ssh/config
}

randpass () {
  openssl rand -base64 32 | tr -d '\n' | sed 's/=//g' 
}

build-ssh-config () {
  echo "building .ssh/config"
  rm ~/.ssh/config

  echo "# autogenerated by build-ssh-config" > ~/.ssh/config
  for file in ~/.ssh/config.d/*; do
    echo "adding $file"
    cat ${file} >> ~/.ssh/config
  done

  chmod 0600 ~/.ssh/config
}

randpass () {
  openssl rand -base64 32 | tr -d '\n' | sed 's/=//g' 
}

PATH=$PATH:$HOME/kinetic/bin
PATH=/usr/local/Cellar/ruby/2.7.1_2/bin:$PATH
