#!/usr/bin/env bash


alias tn="task context none"
alias mit="task +mit"
alias work="mit +@work"
alias w=work
alias home="mit -@work"
alias h=home
alias kc="task proj:kc"
alias current="task context current"
alias someday="task +someday"
alias projects="task PROJECT"

inbox() {
  if  [ $# -eq 0 ]; then
    task +in
  else
    task add +in "$@"
  fi
}

task-complete() {
  task add "$@"
  task +LATEST done
}

tickle() {
  deadline=$1
  shift
  inbox +tickle wait:$deadline "$@"
}

research-and-design() {
  if  [ $# -eq 0 ]; then
    task +rnd
  else
    task add +rnd +next +@computer +@online "$@"
  fi
}

webpage_title() {
  wget --quiet -O - https://trevoroke.com | sed -n -e 's!.*<title>\(.*\)</title>.*!\1!p'
}

read-and-review() {
  if  [ $# -eq 0 ]; then
    task +rnr
  else
    link=$1
    shift
    description="Read and Review: $@"
    task add +rnr +next +@online +@computer "$description"
    task +LATEST annotate $link
  fi
}


alias in="inbox"
alias t='task'
alias tc='task-complete'
alias tick='tickle'
alias think='tickle +1d +think' 
alias rnd='research-and-design'
alias rnr='read-and-review'
alias next='task +next'
